services:
  - type: web
    name: csv-report-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0